In [2]:
import os
import pandas as pd
print("HOME:", os.path.expanduser("~"))
print("Existe kaggle.json?", os.path.exists(os.path.expanduser("~/.kaggle/kaggle.json")))
print("KAGGLE_CONFIG_DIR:", os.environ.get("KAGGLE_CONFIG_DIR"))

HOME: C:\Users\T-GAMER
Existe kaggle.json? True
KAGGLE_CONFIG_DIR: None

# Diabetes NO OK
https://www.kaggle.com/datasets/brandao/diabetes/data

muita variável categórica (não seria um problema, mas....)

In [19]:
from kaggle.api.kaggle_api_extended import KaggleApi
import os
os.environ["KAGGLE_CONFIG_DIR"] = "/.kaggle"

api = KaggleApi()
api.authenticate()

# Exemplo de dataset
dataset = "brandao/diabetes"

# Download
api.dataset_download_files(dataset, path="../dados", unzip=True)

Dataset URL: https://www.kaggle.com/datasets/brandao/diabetes

In [20]:
import pandas as pd
import sweetviz as sv

# Carregar dados
df = pd.read_csv("../dados/diabetic_data.csv")
print(df.shape)

# Criar relatório
report = sv.analyze(df)

# Salvar HTML
report.show_html("../dados/diabetic_data_sweetviz.html")

(101766, 50)

[Step 2/3] Processing Pairwise Features      |████████▍ | [ 84%]   01:55 -> (00:21 left)
Done! Use 'show' commands to display/save.   |██████████| [100%]   00:01 -> (00:00 left)

Report ../dados/diabetic_data_sweetviz.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

# German Bank NO OK

https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data

negativo, muitas variáveis categóricas -> e da trabalho interpretar

In [5]:
from ucimlrepo import fetch_ucirepo

# Fetch dataset
statlog_german_credit_data = fetch_ucirepo(id=144)

# Dados
X = statlog_german_credit_data.data.features
y = statlog_german_credit_data.data.targets

# Informações das variáveis
variables = statlog_german_credit_data.variables
# Extrair nomes das variáveis de entrada
feature_names = variables[variables["role"] == "Feature"]["name"].tolist()

# Atribuir como colunas
X.columns = feature_names
df = pd.concat([X, y], axis=1)
print(df.shape)
df.head()

(1000, 21)

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,...,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20,class
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [4]:
variables

,name,role,type,demographic,description,units,missing_values
0,Attribute1,Feature,Categorical,None,Status of existing checking account,None,no
1,Attribute2,Feature,Integer,None,Duration,months,no
2,Attribute3,Feature,Categorical,None,Credit history,None,no
3,Attribute4,Feature,Categorical,None,Purpose,None,no
4,Attribute5,Feature,Integer,None,Credit amount,None,no
5,Attribute6,Feature,Categorical,None,Savings account/bonds,None,no
6,Attribute7,Feature,Categorical,Other,Present employment since,None,no
7,Attribute8,Feature,Integer,None,Installment rate in percentage of disposable i...,None,no
8,Attribute9,Feature,Categorical,Marital Status,Personal status and sex,None,no
9,Attribute10,Feature,Categorical,None,Other debtors / guarantors,None,no
10,Attribute11,Feature,Integer,None,Present residence since,None,no
11,Attribute12,Feature,Categorical,None,Property,None,no
12,Attribute13,Feature,Integer,Age,Age,years,no
13,Attribute14,Feature,Categorical,None,Other installment plans,None,no
14,Attribute15,Feature,Categorical,Other,Housing,None,no
15,Attribute16,Feature,Integer,None,Number of existing credits at this bank,None,no
16,Attribute17,Feature,Categorical,Occupation,Job,None,no
17,Attribute18,Feature,Integer,None,Number of people being liable to provide maint...,None,no
18,Attribute19,Feature,Binary,None,Telephone,None,no
19,Attribute20,Feature,Binary,Other,foreign worker,None,no
20,class,Target,Binary,None,"1 = Good, 2 = Bad",None,no

In [23]:
report = sv.analyze(X)

# Salvar HTML
report.show_html("../dados/credit_data.html")

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:00 -> (00:00 left)

Report ../dados/credit_data.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

# Credit Default Risk -> muitas bases
https://www.kaggle.com/competitions/home-credit-default-risk/data -> pode ser uma boa para avaliar, mas unir as tabelas pode demorar!

a base de dados principal: (307511, 122)

![Home Credit Default Risk](../dados/credit-default/home_credit.png)

In [11]:
from kaggle.api.kaggle_api_extended import KaggleApi
import os

## Garantir que o Kaggle ache o kaggle.json
#os.environ["KAGGLE_CONFIG_DIR"] = "/.kaggle"
#
## Autenticação
#api = KaggleApi()
#api.authenticate()
#
## Baixar arquivos da competição
#api.competition_download_files(
#    competition="home-credit-default-risk",
#    path="../dados",
#)

In [8]:
import zipfile
import shutil
import os

zip_path = "../dados/home-credit-default-risk.zip"
extract_path = "../dados/credit-default/"

#with zipfile.ZipFile(zip_path, "r") as zip_ref:
#    zip_ref.extractall(extract_path)

#shutil.move(zip_path, extract_path)

In [9]:
import pandas as pd

def read_csv_robusto(path):
    encodings = ["utf-8", "latin1", "ISO-8859-1", "cp1252"]

    for enc in encodings:
        try:
            return pd.read_csv(path, encoding=enc)
        except UnicodeDecodeError:
            continue

    # último recurso: ignorar caracteres inválidos
    return pd.read_csv(path, encoding="utf-8", encoding_errors="ignore")

In [10]:
import os
import pandas as pd
import sweetviz as sv

data_dir = extract_path
csv_files = [f for f in os.listdir(data_dir) if f.lower().endswith(".csv")]

for csv_file in csv_files:
    csv_path = os.path.join(data_dir, csv_file)
    print(f"\nLendo {csv_file}...")

    try:
        df = read_csv_robusto(csv_path)
        print("Shape:", df.shape)

        # Já rodei a análise
        #report = sv.analyze(df)

        #html_name = csv_file.replace(".csv", "_sweetviz.html")
        #html_path = os.path.join(data_dir, html_name)

        #report.show_html(html_path, open_browser=False)
        #print(f"Relatório salvo em: {html_path}")

    except Exception as e:
        print(f"❌ Erro em {csv_file}: {e}")

Lendo application_test.csv...
Shape: (48744, 121)

Lendo application_train.csv...
Shape: (307511, 122)

Lendo bureau.csv...
Shape: (1716428, 17)

Lendo bureau_balance.csv...
Shape: (27299925, 3)

Lendo credit_card_balance.csv...
Shape: (3840312, 23)

Lendo HomeCredit_columns_description.csv...
Shape: (219, 5)

Lendo installments_payments.csv...
Shape: (13605401, 8)

Lendo POS_CASH_balance.csv...
Shape: (10001358, 8)

Lendo previous_application.csv...
Shape: (1670214, 37)

Lendo sample_submission.csv...
Shape: (48744, 2)

# Loan Approval Dataset
https://www.kaggle.com/datasets/rohitgrewal/loan-approval-dataset/data

(4269, 13) --> interessante, bem interessante

In [32]:
from kaggle.api.kaggle_api_extended import KaggleApi
import os
os.environ["KAGGLE_CONFIG_DIR"] = "/.kaggle"

api = KaggleApi()
api.authenticate()

# Exemplo de dataset
dataset = "rohitgrewal/loan-approval-dataset"

# Download
api.dataset_download_files(dataset, path="../dados", unzip=True)

Dataset URL: https://www.kaggle.com/datasets/rohitgrewal/loan-approval-dataset

In [33]:
import pandas as pd
import sweetviz as sv

# Carregar dados
df = pd.read_csv("../dados/loan_approval_dataset.csv")
print(df.shape)

# Criar relatório
report = sv.analyze(df)

# Salvar HTML
report.show_html("../dados/loan_approval_dataset_sweetviz.html")

(4269, 13)

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:00 -> (00:00 left)

Report ../dados/loan_approval_dataset_sweetviz.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

# Flight Delay NO OK
(30132631, 40) --> enorme, o interessante é amostrar! -> mais dificil de interpretar as features
https://www.kaggle.com/datasets/arvindnagaonkar/flight-delay/data?select=features_added.parquet


Modelo de regressão, aparentemente a target é ArrDelay, mas precisaria entender um pouco mais de cada feature

In [ ]:
from kaggle.api.kaggle_api_extended import KaggleApi
import os
os.environ["KAGGLE_CONFIG_DIR"] = "/.kaggle"

api = KaggleApi()
api.authenticate()

# Exemplo de dataset
dataset = "arvindnagaonkar/flight-delay"

# Download
api.dataset_download_files(dataset, path="../dados/flight_delay", unzip=True)

Dataset URL: https://www.kaggle.com/datasets/arvindnagaonkar/flight-delay

In [12]:
import pandas as pd
import sweetviz as sv

# Carregar dados
df = pd.read_parquet("../dados/flight_delay/features_added.parquet")
print(df.shape)

# Criar relatório
#report = sv.analyze(df)

# Salvar HTML
#report.show_html("../dados/flight_delay/features_added_sweetviz.html")

(30132631, 40)

In [13]:
import pandas as pd
import sweetviz as sv

# Carregar dados
df = pd.read_parquet("../dados/flight_delay/Flight_Delay.parquet")
print(df.shape)

# Criar relatório
report = sv.analyze(df)

# Salvar HTML
report.show_html("../dados/flight_delay/Flight_Delay_sweetviz.html")

(30132672, 29)

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:02 -> (00:00 left)

Report ../dados/flight_delay/Flight_Delay_sweetviz.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [14]:
df1 = pd.read_parquet("../dados/flight_delay/Flight_Delay.parquet")
print(df1.shape)

(30132672, 29)

In [15]:
df1.columns

Index(['Year', 'Month', 'DayofMonth', 'FlightDate',
       'Marketing_Airline_Network', 'OriginCityName', 'DestCityName',
       'CRSDepTime', 'DepTime', 'DepDelay', 'DepDelayMinutes', 'TaxiOut',
       'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay',
       'ArrDelayMinutes', 'CRSElapsedTime', 'ActualElapsedTime', 'AirTime',
       'Distance', 'DistanceGroup', 'CarrierDelay', 'WeatherDelay', 'NASDelay',
       'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [17]:
df2 = pd.read_parquet("../dados/flight_delay/features_added.parquet")
print(df1.shape)

(30132672, 29)

In [ ]:
df2.columns
# Supondo que df1 e df2 já existem
# Ver quais colunas existem em df2 e não em df1
colunas_df2_nao_em_df1 = set(df2.columns) - set(df1.columns)
print('Colunas em df2 e não em df1:', colunas_df2_nao_em_df1)

# Ver quais colunas existem em df1 e não em df2
colunas_df1_nao_em_df2 = set(df1.columns) - set(df2.columns)
print('Colunas em df1 e não em df2:', colunas_df1_nao_em_df2)

Colunas em df2 e não em df1: {'Holidays', 'CRSElapsedTimeGorup', 'CRSArrTimeHourDis', 'CRSDepTimeHour', 'WheelsOffMinute', 'CRSArrTimeHour', 'WheelsOffHourDis', 'CRSDepTimeMinute', 'WheelsOnHour', 'CRSArrTimeMinute', 'WheelsOnHourDis', 'CRSDepTimeHourDis', 'DayofWeek', 'WheelsOffHour', 'WheelsOnMinute'}
Colunas em df1 e não em df2: {'CRSDepTime', 'WheelsOn', 'CRSArrTime', 'WheelsOff'}

: